### ISSUE TITLE
[Question] Will disable the recipe remove the item entirely?

### ISSUE THREAD

**Issue by ardissaps** [NerjalNosk/RecipeDisabler#1]
Would be great if so to remove duplicate like many mods add copper equipment which I prefer only 1 of them.

**Comment by NerjalNosk** [comment]
*Sorry for the late answer.*

No, this mod only changes the recipes, or more precisely the resources management (since JSON recipes, even stored in a mod jar, as considered as "resources" to the game).
Hence that mod can also be used only server-side, and its config doesn't need to be the same than the client.
Although it won't be able to do anything to hardcoded recipes (the vanilla holds a few already, such as some coloring recipes)

If you want to prevent registering some specific items, you shall either find some tricky way using a mod such as KubeJS, or make/have one made for that. *Which for you can commission me if you want, by mail, at nosk.nerjal@gmx.com*
