### ISSUE TITLE
Port to 1.20.1

### ISSUE THREAD

**Issue by poly2it** [NerjalNosk/RecipeDisabler#3]
Thank you for the mod. It's the most user-friendly way to disable recipes. I'd love to be able to use it in future versions of my mod-pack.

**Comment by NerjalNosk** [comment]
Hello, thank you for your feedback. And sorry for only seeing it now.

I am glad you like it. Worry not, I do intend to take development at hand again, I only cannot do it right now, for I am working on another project, that will, in the future, be useful for a better work on that one as well.
I am indeed working on a library mod that will allow me to much more easily set up at least the config part of that one mod.
I do wish to publish it as soon as possible, but development as well as other personal matters have been a little tedious lately, thus delaying my progress.
I do hope to make it available before the end of the year though, especially that library mod that I want to publish before the end of October, mid-October if possible

**Comment by t-ospita** [comment]
Hey! I would like to thank you for your mod too. 
How is the progress to update the mod going? Im opening a server in a few weeks and I would like to know if your mod will be updated. 
Thx in advance! :]

**Comment by NerjalNosk** [comment]
Hi

Thank you for your interest in that mod.

As I said back in August, I do have plans to update this mod. However, as plans and workload for the library I want to create went up, available time went the other way around, making me far from done with it, even to this day.

But fear not! As I myself also consider it is a shame people have to resort to mods such as KubeJS or CraftTweaker only ever to disable recipes, or resources of any kind in that matter, I have decided that I will be making a legacy port of this mod for 1.20 and versions to come until I am able to produce a real update, pretty much rewriting the full codebase from the ground up using that library that is still in development.
Said legacy port, however, will be made with the strict minimum for the mod to match its original functionalities, so please do not expect any real improvement using such port, when it'll be out.

As for an ETA, I cannot give you any guarantee, for I am a tad busy these days (hence me only answering today despite seeing the message on the very day you posted it). But on the modding side, I right now am working on updating my [BLAHAJ Fabric port](https://github.com/RecraftorsMC/blahaj), which has been outdated for quite a while. But as soon as this will be done, I shall move onto producing this legacy port. However, there is one other matter that might delay these plans a bit more, which would be me changing most of my projects' licensing, in order to enforce regulations that would better match my expectations.

Last but not least, if you came here from the CurseForge scene, you may or may not have seen it, but I will not be posting any future update there, but only on [Modrinth](https://modrinth.com). And nor will I be accepting people republishing my mods or their ports there, hence the will to change licensing.

Thank you for your comprehension, and I hope not to let you down
